### ISSUE TITLE
Automate synchronizing dependency versions

### ISSUE THREAD

**Issue by anehx** [adfinis/Outdated#15]
Since we pass a repository URL for a project, we are able to automate the synchronization of dependency versions with Github (for now only Github). We can use the public Github GraphQL API to get the versions of the dependencies and then use the NPM/PyPI/endoflife.date APIs to fetch the release and optionally EOL dates of those versions.

Let's implement the following tools to sync dependency versions:$

- A django command to sync one or all projects
- A custom API endpoint to sync one certain project

Those tools need to use the same code in the background.

**Comment by C0rydoras** [comment]
Both of the tools have been implemented [here](https://github.com/adfinis/Outdated/pull/16)
