### ISSUE TITLE
Run/Build Instructions

### ISSUE THREAD

**Issue by in0rdr** [adfinis/Outdated#17]
I was following along the instructions in the Readme.

To build this project, I had to perform 2 additional steps (OpenSuse laptop with Docker version 20.10.23-ce):
```bash
# For some reason this is a requirement in the docker-compose file
export $UID=$(id -u)

# Not sure why but the docker-compose binary is really called that way on my distro
sed -i 's/docker compose/docker-compose/g' Makefile
```

**Comment by C0rydoras** [comment]
1. Thank you, i forgot to add `echo "UID=$(id -u)" > .env` to the readme.
2. As far as i know the second command shouldn't be necessary unless you run on an outdated version compose.

**Comment by C0rydoras** [comment]
I have updated the run/build instructions here: #28
