### ISSUE TITLE
k8s probes

### ISSUE THREAD

**Issue by c0rydoras** [adfinis/outdated#230]
### Backend

use `django-watchman` for health endpoint(s)

### Frontend

`GET /index.html`

**Comment by hairmare** [comment]
There are 3 k8s probes
* readiness get requested on startup until the app is ready
* if you this will take long, then you can configure startup and it'll wait for that
* liveness is run once the app is up. if it fails, then we first stop sending traffic to the app and then restart it if that doesn't help

in django cases, we often don't configure startup and use the same URL for readiness and liveness.

for the frontend `/index.html` or `/` is more than fine, we rely on nginx to do us properly
